# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2019-2024 The Foundation for Public Code <info@publiccode.net>, https://standard.publiccode.net/AUTHORS

title: Standard for Public Code

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

remote_theme: just-the-docs/just-the-docs

toc: true

include_badges: true
include_translations: true

defaults:
  -
    scope:
      path: '/criteria/*'
    values:
      show_prev_next: true
